# Generated by Django 4.0.4 on 2022-04-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('grupo', models.IntegerField()),
                ('fechaDeRegistro', models.DateField()),
                ('salario', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TiposDTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=30)),
                ('horas_d_empleo', models.IntegerField()),
                ('edadEnElTrabajo', models.IntegerField()),
            ],
        ),
    ]
